# Generated by Django 6.0 on 2025-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tag_ids",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tasks", to="tasks.tag"
            ),
        ),
    ]
